# Schema file for the configuration files of the persistent_login module.

persistent_login.settings:
  type: config_object
  label: 'Persistent Login Settings'
  mapping:
    lifetime:
      type: integer
      label: 'The maximum number of days for which a persistent login session is valid'
    max_tokens:
      type: integer
      label: 'The maximum number of tokens per user'
    login_form:
      type: mapping
      label: 'Login Form'
      mapping:
        field_label:
          type: label
          label: 'The login form field label'
    cookie_prefix:
      type: string
      label: 'Cookie Prefix'
